### PR TITLE
Attachment

### PR DESCRIPTION
**Pull request by nathanwilk7**
Questions for Reviewers

1. Because there is no notion of "Top Level" in sboljs, these changes technically allow for attachment links to be included in any class, not only "Top Level" classes. Do you want to move forward with this or would you like me to spend some time thinking about how to refactor sboljs so we can have "Top Level" specific behavior?
2. Is the JSON serialization correct? If not, is it worth fixing or should we worry about that later?

### CODE REVIEW

**Review by cjmyers — CHANGES_REQUESTED** [review]
I did not see a link function in Identified.js.  Other than that, it looks good.

**Comment by nathanwilk7** [comment]
Regarding the link function in Identified.js, are you referring to the link function on line number 322?

**Review by cjmyers — APPROVED** [review]
Oops, I see it now.

**Comment by jamesamcl** [comment]
> Because there is no notion of "Top Level" in sboljs, these changes technically allow for attachment links to be included in any class, not only "Top Level" classes. Do you want to move forward with this or would you like me to spend some time thinking about how to refactor sboljs so we can have "Top Level" specific behavior?

I think it would be as simple as making a TopLevel class that derives from Identified, and then changing ComponentDefinition etc. to derive from that instead.  That would be a good thing to do.

> Is the JSON serialization correct? If not, is it worth fixing or should we worry about that later?

I'm not sure if any of the JSON serialization is correct now.  We never really used it for anything, and none of the other libraries support it.  Let's worry about it later - it might end up getting removed from the library.

**Comment by cjmyers** [comment]
On Jan 18, 2018, at 6:48 AM, James Alastair McLaughlin <notifications@github.com> wrote:
> 
> Because there is no notion of "Top Level" in sboljs, these changes technically allow for attachment links to be included in any class, not only "Top Level" classes. Do you want to move forward with this or would you like me to spend some time thinking about how to refactor sboljs so we can have "Top Level" specific behavior?
> 
> I think it would be as simple as making a TopLevel class that derives from Identified, and then changing ComponentDefinition etc. to derive from that instead. That would be a good thing to do.
> 
It might be a good thing, but sboljs is fairly permissive already, so it is likely not a priority.  Anything generated using sboljs should probably be validated with libSBOLj in any case.  I will log an issue to create TopLevel class, but we don’t need to rush on this.
> Is the JSON serialization correct? If not, is it worth fixing or should we worry about that later?
> 
> I'm not sure if any of the JSON serialization is correct now. We never really used it for anything, and none of the other libraries support it. Let's worry about it later - it might end up getting removed from the library.
> 
> 
> 
There is really no notion of correct for JSON, since there is no approved JSON serialization for SBOL, so it is not high priority.  However, it is not too much extra work to keep updating it when we update the XML serialization.

**Comment by nathanwilk7** [comment]
Cool, thanks for the thoughts James and Chris. I'll wait to do the TopLevel refactor until it becomes a priority.

**Pull request merged**
